### ISSUE TITLE
No module name 'alembic'

### ISSUE THREAD

**Issue by Insiyaa** [pietrobassi/bunnybook#1]
Hi, thanks for this project. While setting up backend for dev, I am facing this error:
```Traceback (most recent call last):
  File "init_db.py", line 1, in <module>
    import alembic.config
ModuleNotFoundError: No module named 'alembic'
```
Can you please help?

**Comment by adam-s** [comment]
Upgrade Pillow to version 9.3.0 and websockets to 10.4 in requirements.txt.
